// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `SAS.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __SAS_h__
#define __SAS_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/IncomingAsync.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace SAS
{

class SASSession;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::SAS::SASSession>&);
::IceProxy::Ice::Object* upCast(::IceProxy::SAS::SASSession*);

}

}

namespace SAS
{

class SASSession;
bool operator==(const SASSession&, const SASSession&);
bool operator<(const SASSession&, const SASSession&);
::Ice::Object* upCast(::SAS::SASSession*);
typedef ::IceInternal::Handle< ::SAS::SASSession> SASSessionPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::SAS::SASSession> SASSessionPrx;
void __patch(SASSessionPtr&, const ::Ice::ObjectPtr&);

}

namespace SAS
{

class AMD_SASSession_SendSMS : virtual public ::Ice::AMDCallback
{
public:

    virtual void ice_response(const ::std::string&) = 0;
};

typedef ::IceUtil::Handle< ::SAS::AMD_SASSession_SendSMS> AMD_SASSession_SendSMSPtr;

}

namespace IceAsync
{

namespace SAS
{

class AMD_SASSession_SendSMS : public ::SAS::AMD_SASSession_SendSMS, public ::IceInternal::IncomingAsync
{
public:

    AMD_SASSession_SendSMS(::IceInternal::Incoming&);

    virtual void ice_response(const ::std::string&);
};

}

}

namespace SAS
{

class Callback_SASSession_SendSMS_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_SASSession_SendSMS_Base> Callback_SASSession_SendSMSPtr;

class Callback_SASSession_QuerySMS_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_SASSession_QuerySMS_Base> Callback_SASSession_QuerySMSPtr;

}

namespace IceProxy
{

namespace SAS
{

class SASSession : virtual public ::IceProxy::Ice::Object
{
public:

    void SendSMS(const ::std::string& request, ::std::string& response)
    {
        SendSMS(request, response, 0);
    }
    void SendSMS(const ::std::string& request, ::std::string& response, const ::Ice::Context& __ctx)
    {
        SendSMS(request, response, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_SendSMS(const ::std::string& request, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_SendSMS(request, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_SendSMS(const ::std::string& request, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_SendSMS(request, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_SendSMS(const ::std::string& request, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_SendSMS(request, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_SendSMS(const ::std::string& request, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_SendSMS(request, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_SendSMS(const ::std::string& request, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::std::string&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::SAS::SASSessionPrx __proxy = ::SAS::SASSessionPrx::uncheckedCast(__result->getProxy());
                ::std::string response;
                try
                {
                    __proxy->end_SendSMS(response, __result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(response);
                }
            }
        
        private:
            
            ::std::function<void (const ::std::string&)> _response;
        };
        return begin_SendSMS(request, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_SendSMS(const ::std::string& request)
    {
        return begin_SendSMS(request, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_SendSMS(const ::std::string& request, const ::Ice::Context& __ctx)
    {
        return begin_SendSMS(request, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_SendSMS(const ::std::string& request, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_SendSMS(request, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_SendSMS(const ::std::string& request, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_SendSMS(request, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_SendSMS(const ::std::string& request, const ::SAS::Callback_SASSession_SendSMSPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_SendSMS(request, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_SendSMS(const ::std::string& request, const ::Ice::Context& __ctx, const ::SAS::Callback_SASSession_SendSMSPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_SendSMS(request, &__ctx, __del, __cookie);
    }

    void end_SendSMS(::std::string& response, const ::Ice::AsyncResultPtr&);
    
private:

    void SendSMS(const ::std::string&, ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_SendSMS(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void QuerySMS(const ::std::string& request, ::std::string& response)
    {
        QuerySMS(request, response, 0);
    }
    void QuerySMS(const ::std::string& request, ::std::string& response, const ::Ice::Context& __ctx)
    {
        QuerySMS(request, response, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_QuerySMS(const ::std::string& request, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_QuerySMS(request, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_QuerySMS(const ::std::string& request, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_QuerySMS(request, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_QuerySMS(const ::std::string& request, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_QuerySMS(request, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_QuerySMS(const ::std::string& request, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_QuerySMS(request, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_QuerySMS(const ::std::string& request, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::std::string&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::SAS::SASSessionPrx __proxy = ::SAS::SASSessionPrx::uncheckedCast(__result->getProxy());
                ::std::string response;
                try
                {
                    __proxy->end_QuerySMS(response, __result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(response);
                }
            }
        
        private:
            
            ::std::function<void (const ::std::string&)> _response;
        };
        return begin_QuerySMS(request, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_QuerySMS(const ::std::string& request)
    {
        return begin_QuerySMS(request, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_QuerySMS(const ::std::string& request, const ::Ice::Context& __ctx)
    {
        return begin_QuerySMS(request, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_QuerySMS(const ::std::string& request, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_QuerySMS(request, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_QuerySMS(const ::std::string& request, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_QuerySMS(request, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_QuerySMS(const ::std::string& request, const ::SAS::Callback_SASSession_QuerySMSPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_QuerySMS(request, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_QuerySMS(const ::std::string& request, const ::Ice::Context& __ctx, const ::SAS::Callback_SASSession_QuerySMSPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_QuerySMS(request, &__ctx, __del, __cookie);
    }

    void end_QuerySMS(::std::string& response, const ::Ice::AsyncResultPtr&);
    
private:

    void QuerySMS(const ::std::string&, ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_QuerySMS(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<SASSession> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<SASSession*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<SASSession> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<SASSession*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<SASSession> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<SASSession*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<SASSession> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<SASSession*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<SASSession> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<SASSession*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<SASSession> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<SASSession*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<SASSession> ice_secure(bool __secure) const
    {
        return dynamic_cast<SASSession*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<SASSession> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<SASSession*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<SASSession> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<SASSession*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<SASSession> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<SASSession*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<SASSession> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<SASSession*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<SASSession> ice_twoway() const
    {
        return dynamic_cast<SASSession*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<SASSession> ice_oneway() const
    {
        return dynamic_cast<SASSession*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<SASSession> ice_batchOneway() const
    {
        return dynamic_cast<SASSession*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<SASSession> ice_datagram() const
    {
        return dynamic_cast<SASSession*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<SASSession> ice_batchDatagram() const
    {
        return dynamic_cast<SASSession*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<SASSession> ice_compress(bool __compress) const
    {
        return dynamic_cast<SASSession*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<SASSession> ice_timeout(int __timeout) const
    {
        return dynamic_cast<SASSession*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<SASSession> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<SASSession*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<SASSession> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<SASSession*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace SAS
{

class SASSession : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void SendSMS(const ::std::string&, ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void QuerySMS(const ::std::string&, ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace SAS
{

class SASSession : virtual public ::IceDelegate::SAS::SASSession,
                   virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void SendSMS(const ::std::string&, ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void QuerySMS(const ::std::string&, ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace SAS
{

class SASSession : virtual public ::IceDelegate::SAS::SASSession,
                   virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void SendSMS(const ::std::string&, ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void QuerySMS(const ::std::string&, ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace SAS
{

class SASSession : virtual public ::Ice::Object
{
public:

    typedef SASSessionPrx ProxyType;
    typedef SASSessionPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void SendSMS_async(const ::SAS::AMD_SASSession_SendSMSPtr&, const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___SendSMS(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void QuerySMS(const ::std::string&, ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___QuerySMS(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const SASSession& l, const SASSession& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const SASSession& l, const SASSession& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace SAS
{

template<class T>
class CallbackNC_SASSession_SendSMS : public Callback_SASSession_SendSMS_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::std::string&);

    CallbackNC_SASSession_SendSMS(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::SAS::SASSessionPrx __proxy = ::SAS::SASSessionPrx::uncheckedCast(__result->getProxy());
        ::std::string response;
        try
        {
            __proxy->end_SendSMS(response, __result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(response);
        }
    }

    Response response;
};

template<class T> Callback_SASSession_SendSMSPtr
newCallback_SASSession_SendSMS(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_SASSession_SendSMS<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_SASSession_SendSMSPtr
newCallback_SASSession_SendSMS(T* instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_SASSession_SendSMS<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_SASSession_SendSMS : public Callback_SASSession_SendSMS_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::std::string&, const CT&);

    Callback_SASSession_SendSMS(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::SAS::SASSessionPrx __proxy = ::SAS::SASSessionPrx::uncheckedCast(__result->getProxy());
        ::std::string response;
        try
        {
            __proxy->end_SendSMS(response, __result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(response, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_SASSession_SendSMSPtr
newCallback_SASSession_SendSMS(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_SASSession_SendSMS<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_SASSession_SendSMSPtr
newCallback_SASSession_SendSMS(T* instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_SASSession_SendSMS<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_SASSession_QuerySMS : public Callback_SASSession_QuerySMS_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::std::string&);

    CallbackNC_SASSession_QuerySMS(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::SAS::SASSessionPrx __proxy = ::SAS::SASSessionPrx::uncheckedCast(__result->getProxy());
        ::std::string response;
        try
        {
            __proxy->end_QuerySMS(response, __result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(response);
        }
    }

    Response response;
};

template<class T> Callback_SASSession_QuerySMSPtr
newCallback_SASSession_QuerySMS(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_SASSession_QuerySMS<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_SASSession_QuerySMSPtr
newCallback_SASSession_QuerySMS(T* instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_SASSession_QuerySMS<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_SASSession_QuerySMS : public Callback_SASSession_QuerySMS_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::std::string&, const CT&);

    Callback_SASSession_QuerySMS(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::SAS::SASSessionPrx __proxy = ::SAS::SASSessionPrx::uncheckedCast(__result->getProxy());
        ::std::string response;
        try
        {
            __proxy->end_QuerySMS(response, __result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(response, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_SASSession_QuerySMSPtr
newCallback_SASSession_QuerySMS(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_SASSession_QuerySMS<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_SASSession_QuerySMSPtr
newCallback_SASSession_QuerySMS(T* instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_SASSession_QuerySMS<T, CT>(instance, cb, excb, sentcb);
}

}

#endif
